# Site settings
title: Mathematics and Problem Solving
email: your-email@domain.com
description: >
  A first-year course in maths for computer science students.
lang: en-GB

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://mathsforcs.netlify.app # the base hostname & protocol for your site
git_address: https://github.com/davidgundry/mathematics-and-problem-solving
git_edit_address: https://github.com/davidgundry/mathematics-and-problem-solving/blob/gh-pages

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/London
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _course
    type: course
  values:
    layout: docs
    sectionid: course
    seo:
      type: "WebPage"

collections:
  course:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
